# Generated by Django 3.0 on 2019-12-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForthStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('down_link', models.CharField(max_length=300)),
                ('course_name', models.CharField(max_length=100)),
                ('course_author', models.CharField(max_length=100)),
                ('course_link', models.CharField(max_length=300)),
                ('book_name', models.CharField(max_length=100)),
                ('book_isbn', models.IntegerField()),
                ('book_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SecondStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('down_link', models.CharField(max_length=300)),
                ('course_name', models.CharField(max_length=100)),
                ('course_author', models.CharField(max_length=100)),
                ('course_link', models.CharField(max_length=300)),
                ('book_name', models.CharField(max_length=100)),
                ('book_isbn', models.IntegerField()),
                ('book_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('down_link', models.CharField(max_length=300)),
                ('course_name', models.CharField(max_length=100)),
                ('course_author', models.CharField(max_length=100)),
                ('course_link', models.CharField(max_length=300)),
                ('book_name', models.CharField(max_length=100)),
                ('book_isbn', models.IntegerField()),
                ('book_link', models.CharField(max_length=300)),
            ],
        ),
    ]
