# Generated by Django 3.0 on 2019-12-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_forthstage_secondstage_thirdstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsatage',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='forthstage',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='secondstage',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='thirdstage',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
    ]
