# Generated by Django 3.0 on 2019-12-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20191214_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsatage',
            name='img_course',
            field=models.ImageField(blank=True, default='None', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='forthstage',
            name='img_course',
            field=models.ImageField(blank=True, default='None', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='secondstage',
            name='img_course',
            field=models.ImageField(blank=True, default='None', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='thirdstage',
            name='img_course',
            field=models.ImageField(blank=True, default='None', null=True, upload_to=''),
        ),
    ]
